/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   checking.c                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tpacaud <tpacaud@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/05/27 19:55:06 by tpacaud           #+#    #+#             */
/*   Updated: 2019/05/28 14:31:36 by tpacaud          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./Includes/ft_printf.h"

void    mine(int nb)
{
    ft_printf("space% d\n", nb);
    ft_printf("plus:%+d\n", nb);
	ft_printf("precision:%.5d\n", nb);
	ft_printf("space + prec:% .5d\n", nb);
	ft_printf("Plus + prec / grande:%+.5d\n", nb);
	ft_printf("Plus + prec / petite:%+.0d\n", nb);
	ft_printf("Prec + 0:%0.5d\n", nb);
	ft_printf("Prec + minus:%-.5d\n", nb);
	ft_printf("size:%5d\n", nb);
	ft_printf("size + space:% 5d\n", nb);
	ft_printf("size + plus:%+5d\n", nb);
	ft_printf("size + minus:%-5d\n", nb);
	ft_printf("size + 0:%05d\n", nb);
	ft_printf("size + 0 + plus:%+05d\n", nb);
	ft_printf("size + 0 + plus:%0+5d\n", nb);
	ft_printf("size + 0 + prec:%05.3d\n", nb);
	ft_printf("size + minus + prec:%-5.3d\n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3d\n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3d\n", nb);
	ft_printf("size + espace + zero + prec:% 05.3d\n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3d\n", nb);
	ft_printf("space% i\n", nb);
	ft_printf("plus:%+i\n", nb);
	ft_printf("precision:%.5i\n", nb);
	ft_printf("space + prec:% .5i\n", nb);
	ft_printf("Plus + prec / grande:%+.5i\n", nb);
	ft_printf("Plus + prec / petite:%+.0i\n", nb);
	ft_printf("Prec + 0:%0.5i\n", nb);
	ft_printf("Prec + minus:%-.5i\n", nb);
	ft_printf("size:%5i\n", nb);
	ft_printf("size + space:% 5i\n", nb);
	ft_printf("size + plus:%+5i\n", nb);
	ft_printf("size + minus:%-5i\n", nb);
	ft_printf("size + 0:%05i\n", nb);
	ft_printf("size + 0 + plus:%+05i\n", nb);
	ft_printf("size + 0 + plus:%0+5i\n", nb);
	ft_printf("size + 0 + prec:%05.3i\n", nb);
	ft_printf("size + minus + prec:%-5.3i\n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3i\n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3i\n", nb);
	ft_printf("size + espace + zero + prec:% 05.3i\n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3i\n", nb);
	ft_printf("space% d \n", nb);
	ft_printf("plus:%+d \n", nb);
	ft_printf("precision:%.5d \n", nb);
	ft_printf("space + prec:% .5d \n", nb);
	ft_printf("Plus + prec / grande:%+.5d \n", nb);
	ft_printf("Prec + 0:%0.5d \n", nb);
	ft_printf("Prec + minus:%-.5d \n", nb);
	ft_printf("size:%5d \n", nb);
	ft_printf("size + space:% 5d \n", nb);
	ft_printf("size + plus:%+5d \n", nb);
	ft_printf("size + minus:%-5d \n", nb);
	ft_printf("size + 0:%05d \n", nb);
	ft_printf("size + 0 + plus:%+05d \n", nb);
	ft_printf("size + 0 + plus:%0+5d \n", nb);
	ft_printf("size + 0 + prec:%05.3d \n", nb);
	ft_printf("size + minus + prec:%-5.3d \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3d \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3d \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3d \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3d \n", nb);
	ft_printf("space% d \n", nb);
	ft_printf("plus:%+d \n", nb);
	ft_printf("precision:%.5d \n", nb);
	ft_printf("space + prec:% .5d \n", nb);
	ft_printf("Plus + prec / grande:%+.5d \n", nb);
	ft_printf("Prec + 0:%0.5d \n", nb);
	ft_printf("Prec + minus:%-.5d \n", nb);
	ft_printf("size:%5d \n", nb);
	ft_printf("size + space:% 5d \n", nb);
	ft_printf("size + plus:%+5d \n", nb);
	ft_printf("size + minus:%-5d \n", nb);
	ft_printf("size + 0:%05d \n", nb);
	ft_printf("size + 0 + plus:%+05d \n", nb);
	ft_printf("size + 0 + plus:%0+5d \n", nb);
	ft_printf("size + 0 + prec:%05.3d \n", nb);
	ft_printf("size + minus + prec:%-5.3d \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3d \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3d \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3d \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3d \n", nb);
	ft_printf("space% d \n", nb);
	ft_printf("plus:%+d \n", nb);
	ft_printf("precision:%.5d \n", nb);
	ft_printf("space + prec:% .5d \n", nb);
	ft_printf("Plus + prec / grande:%+.5d \n", nb);
	ft_printf("Prec + 0:%0.5d \n", nb);
	ft_printf("Prec + minus:%-.5d \n", nb);
	ft_printf("size:%5d \n", nb);
	ft_printf("size + space:% 5d \n", nb);
	ft_printf("size + plus:%+5d \n", nb);
	ft_printf("size + minus:%-5d \n", nb);
	ft_printf("size + 0:%05d \n", nb);
	ft_printf("size + 0 + plus:%+05d \n", nb);
	ft_printf("size + 0 + plus:%0+5d \n", nb);
	ft_printf("size + 0 + prec:%05.3d \n", nb);
	ft_printf("size + minus + prec:%-5.3d \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3d \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3d \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3d \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3d \n", nb);
	ft_printf("space% d \n", nb);
	ft_printf("plus:%+d \n", nb);
	ft_printf("precision:%.5d \n", nb);
	ft_printf("space + prec:% .5d \n", nb);
	ft_printf("Plus + prec / grande:%+.5d \n", nb);
	ft_printf("Prec + 0:%0.5d \n", nb);
	ft_printf("Prec + minus:%-.5d \n", nb);
	ft_printf("size:%5d \n", nb);
	ft_printf("size + space:% 5d \n", nb);
	ft_printf("size + plus:%+5d \n", nb);
	ft_printf("size + minus:%-5d \n", nb);
	ft_printf("size + 0:%05d \n", nb);
	ft_printf("size + 0 + plus:%+05d \n", nb);
	ft_printf("size + 0 + plus:%0+5d \n", nb);
	ft_printf("size + 0 + prec:%05.3d \n", nb);
	ft_printf("size + minus + prec:%-5.3d \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3d \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3d \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3d \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3d \n", nb);
	ft_printf("space% ld \n", nb);
	ft_printf("plus:%+ld \n", nb);
	ft_printf("precision:%.5ld \n", nb);
	ft_printf("space + prec:% .5ld \n", nb);
	ft_printf("Plus + prec / grande:%+.5ld \n", nb);
	ft_printf("Prec + 0:%0.5ld \n", nb);
	ft_printf("Prec + minus:%-.5ld \n", nb);
	ft_printf("size:%5ld \n", nb);
	ft_printf("size + space:% 5ld \n", nb);
	ft_printf("size + plus:%+5ld \n", nb);
	ft_printf("size + minus:%-5ld \n", nb);
	ft_printf("size + 0:%05ld \n", nb);
	ft_printf("size + 0 + plus:%+05ld \n", nb);
	ft_printf("size + 0 + plus:%0+5ld \n", nb);
	ft_printf("size + 0 + prec:%05.3ld \n", nb);
	ft_printf("size + minus + prec:%-5.3ld \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3ld \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3ld \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3ld \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3ld \n", nb);
	ft_printf("space% lld \n", nb);
	ft_printf("plus:%+lld \n", nb);
	ft_printf("precision:%.5lld \n", nb);
	ft_printf("space + prec:% .5lld \n", nb);
	ft_printf("Plus + prec / grande:%+.5lld \n", nb);
	ft_printf("Prec + 0:%0.5lld \n", nb);
	ft_printf("Prec + minus:%-.5lld \n", nb);
	ft_printf("size:%5lld \n", nb);
	ft_printf("size + space:% 5lld \n", nb);
	ft_printf("size + plus:%+5lld \n", nb);
	ft_printf("size + minus:%-5lld \n", nb);
	ft_printf("size + 0:%05lld \n", nb);
	ft_printf("size + 0 + plus:%+05lld \n", nb);
	ft_printf("size + 0 + plus:%0+5lld \n", nb);
	ft_printf("size + 0 + prec:%05.3lld \n", nb);
	ft_printf("size + minus + prec:%-5.3lld \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3lld \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3lld \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3lld \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3lld \n", nb);
	ft_printf("space% hhd \n", nb);
	ft_printf("plus:%+hhd \n", nb);
	ft_printf("precision:%.5hhd \n", nb);
	ft_printf("space + prec:% .5hhd \n", nb);
	ft_printf("Plus + prec / grande:%+.5hhd \n", nb);
	ft_printf("Prec + 0:%0.5hhd \n", nb);
	ft_printf("Prec + minus:%-.5hhd \n", nb);
	ft_printf("size:%5hhd \n", nb);
	ft_printf("size + space:% 5hhd \n", nb);
	ft_printf("size + plus:%+5hhd \n", nb);
	ft_printf("size + minus:%-5hhd \n", nb);
	ft_printf("size + 0:%05hhd \n", nb);
	ft_printf("size + 0 + plus:%+05hhd \n", nb);
	ft_printf("size + 0 + plus:%0+5hhd \n", nb);
	ft_printf("size + 0 + prec:%05.3hhd \n", nb);
	ft_printf("size + minus + prec:%-5.3hhd \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3hhd \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3hhd \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3hhd \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3hhd \n", nb);
	ft_printf("space% hd \n", nb);
	ft_printf("plus:%+hd \n", nb);
	ft_printf("precision:%.5hd \n", nb);
	ft_printf("space + prec:% .5hd \n", nb);
	ft_printf("Plus + prec / grande:%+.5hd \n", nb);
	ft_printf("Prec + 0:%0.5hd \n", nb);
	ft_printf("Prec + minus:%-.5hd \n", nb);
	ft_printf("size:%5hd \n", nb);
	ft_printf("size + space:% 5hd \n", nb);
	ft_printf("size + plus:%+5hd \n", nb);
	ft_printf("size + minus:%-5hd \n", nb);
	ft_printf("size + 0:%05hd \n", nb);
	ft_printf("size + 0 + plus:%+05hd \n", nb);
	ft_printf("size + 0 + plus:%0+5hd \n", nb);
	ft_printf("size + 0 + prec:%05.3hd \n", nb);
	ft_printf("size + minus + prec:%-5.3hd \n", nb);
	ft_printf("size + plus + 0 + prec:%+05.3hd \n", nb);
	ft_printf("size + espace + zero + prec:%0 5.3hd \n", nb);
	ft_printf("size + espace + zero + prec:% 05.3hd \n", nb);
	ft_printf("size + minus + plus + prec:%-+5.3hd \n", nb);
	ft_printf("max int :  %d", INT16_MAX);
	ft_printf("min int :  %d", INT16_MIN);
	ft_printf("max int :  %d", INT32_MAX);
	ft_printf("min int :  %d", INT32_MIN);
	// ft_printf("max long :  %ld", LONG_MAX);
	// ft_printf("min long :  %ld", LONG_MIN);
	// ft_printf("max long long :  %lld", __LONG_LONG_MAX__);
	// ft_printf("min long long :  %lld",LLONG_MIN);
}

void    real(int nb)
{
    printf("space% d\n", nb);
    printf("plus:%+d\n", nb);
	printf("precision:%.5d\n", nb);
	printf("space + prec:% .5d\n", nb);
	printf("Plus + prec / grande:%+.5d\n", nb);
	printf("Plus + prec / petite:%+.0d\n", nb);
	printf("Prec + 0:%0.5d\n", nb);
	printf("Prec + minus:%-.5d\n", nb);
	printf("size:%5d\n", nb);
	printf("size + space:% 5d\n", nb);
	printf("size + plus:%+5d\n", nb);
	printf("size + minus:%-5d\n", nb);
	printf("size + 0:%05d\n", nb);
	printf("size + 0 + plus:%+05d\n", nb);
	printf("size + 0 + plus:%0+5d\n", nb);
	printf("size + 0 + prec:%05.3d\n", nb);
	printf("size + minus + prec:%-5.3d\n", nb);
	printf("size + plus + 0 + prec:%+05.3d\n", nb);
	printf("size + espace + zero + prec:%0 5.3d\n", nb);
	printf("size + espace + zero + prec:% 05.3d\n", nb);
	printf("size + minus + plus + prec:%-+5.3d\n", nb);
	printf("space% i\n", nb);
	printf("plus:%+i\n", nb);
	printf("precision:%.5i\n", nb);
	printf("space + prec:% .5i\n", nb);
	printf("Plus + prec / grande:%+.5i\n", nb);
	printf("Plus + prec / petite:%+.0i\n", nb);
	printf("Prec + 0:%0.5i\n", nb);
	printf("Prec + minus:%-.5i\n", nb);
	printf("size:%5i\n", nb);
	printf("size + space:% 5i\n", nb);
	printf("size + plus:%+5i\n", nb);
	printf("size + minus:%-5i\n", nb);
	printf("size + 0:%05i\n", nb);
	printf("size + 0 + plus:%+05i\n", nb);
	printf("size + 0 + plus:%0+5i\n", nb);
	printf("size + 0 + prec:%05.3i\n", nb);
	printf("size + minus + prec:%-5.3i\n", nb);
	printf("size + plus + 0 + prec:%+05.3i\n", nb);
	printf("size + espace + zero + prec:%0 5.3i\n", nb);
	printf("size + espace + zero + prec:% 05.3i\n", nb);
	printf("size + minus + plus + prec:%-+5.3i\n", nb);
	printf("space% d \n", nb);
	printf("plus:%+d \n", nb);
	printf("precision:%.5d \n", nb);
	printf("space + prec:% .5d \n", nb);
	printf("Plus + prec / grande:%+.5d \n", nb);
	printf("Prec + 0:%0.5d \n", nb);
	printf("Prec + minus:%-.5d \n", nb);
	printf("size:%5d \n", nb);
	printf("size + space:% 5d \n", nb);
	printf("size + plus:%+5d \n", nb);
	printf("size + minus:%-5d \n", nb);
	printf("size + 0:%05d \n", nb);
	printf("size + 0 + plus:%+05d \n", nb);
	printf("size + 0 + plus:%0+5d \n", nb);
	printf("size + 0 + prec:%05.3d \n", nb);
	printf("size + minus + prec:%-5.3d \n", nb);
	printf("size + plus + 0 + prec:%+05.3d \n", nb);
	printf("size + espace + zero + prec:%0 5.3d \n", nb);
	printf("size + espace + zero + prec:% 05.3d \n", nb);
	printf("size + minus + plus + prec:%-+5.3d \n", nb);
	printf("space% d \n", nb);
	printf("plus:%+d \n", nb);
	printf("precision:%.5d \n", nb);
	printf("space + prec:% .5d \n", nb);
	printf("Plus + prec / grande:%+.5d \n", nb);
	printf("Prec + 0:%0.5d \n", nb);
	printf("Prec + minus:%-.5d \n", nb);
	printf("size:%5d \n", nb);
	printf("size + space:% 5d \n", nb);
	printf("size + plus:%+5d \n", nb);
	printf("size + minus:%-5d \n", nb);
	printf("size + 0:%05d \n", nb);
	printf("size + 0 + plus:%+05d \n", nb);
	printf("size + 0 + plus:%0+5d \n", nb);
	printf("size + 0 + prec:%05.3d \n", nb);
	printf("size + minus + prec:%-5.3d \n", nb);
	printf("size + plus + 0 + prec:%+05.3d \n", nb);
	printf("size + espace + zero + prec:%0 5.3d \n", nb);
	printf("size + espace + zero + prec:% 05.3d \n", nb);
	printf("size + minus + plus + prec:%-+5.3d \n", nb);
	printf("space% d \n", nb);
	printf("plus:%+d \n", nb);
	printf("precision:%.5d \n", nb);
	printf("space + prec:% .5d \n", nb);
	printf("Plus + prec / grande:%+.5d \n", nb);
	printf("Prec + 0:%0.5d \n", nb);
	printf("Prec + minus:%-.5d \n", nb);
	printf("size:%5d \n", nb);
	printf("size + space:% 5d \n", nb);
	printf("size + plus:%+5d \n", nb);
	printf("size + minus:%-5d \n", nb);
	printf("size + 0:%05d \n", nb);
	printf("size + 0 + plus:%+05d \n", nb);
	printf("size + 0 + plus:%0+5d \n", nb);
	printf("size + 0 + prec:%05.3d \n", nb);
	printf("size + minus + prec:%-5.3d \n", nb);
	printf("size + plus + 0 + prec:%+05.3d \n", nb);
	printf("size + espace + zero + prec:%0 5.3d \n", nb);
	printf("size + espace + zero + prec:% 05.3d \n", nb);
	printf("size + minus + plus + prec:%-+5.3d \n", nb);
	printf("space% d \n", nb);
	printf("plus:%+d \n", nb);
	printf("precision:%.5d \n", nb);
	printf("space + prec:% .5d \n", nb);
	printf("Plus + prec / grande:%+.5d \n", nb);
	printf("Prec + 0:%0.5d \n", nb);
	printf("Prec + minus:%-.5d \n", nb);
	printf("size:%5d \n", nb);
	printf("size + space:% 5d \n", nb);
	printf("size + plus:%+5d \n", nb);
	printf("size + minus:%-5d \n", nb);
	printf("size + 0:%05d \n", nb);
	printf("size + 0 + plus:%+05d \n", nb);
	printf("size + 0 + plus:%0+5d \n", nb);
	printf("size + 0 + prec:%05.3d \n", nb);
	printf("size + minus + prec:%-5.3d \n", nb);
	printf("size + plus + 0 + prec:%+05.3d \n", nb);
	printf("size + espace + zero + prec:%0 5.3d \n", nb);
	printf("size + espace + zero + prec:% 05.3d \n", nb);
	printf("size + minus + plus + prec:%-+5.3d \n", nb);
	printf("space% ld \n", nb);
	printf("plus:%+ld \n", nb);
	printf("precision:%.5ld \n", nb);
	printf("space + prec:% .5ld \n", nb);
	printf("Plus + prec / grande:%+.5ld \n", nb);
	printf("Prec + 0:%0.5ld \n", nb);
	printf("Prec + minus:%-.5ld \n", nb);
	printf("size:%5ld \n", nb);
	printf("size + space:% 5ld \n", nb);
	printf("size + plus:%+5ld \n", nb);
	printf("size + minus:%-5ld \n", nb);
	printf("size + 0:%05ld \n", nb);
	printf("size + 0 + plus:%+05ld \n", nb);
	printf("size + 0 + plus:%0+5ld \n", nb);
	printf("size + 0 + prec:%05.3ld \n", nb);
	printf("size + minus + prec:%-5.3ld \n", nb);
	printf("size + plus + 0 + prec:%+05.3ld \n", nb);
	printf("size + espace + zero + prec:%0 5.3ld \n", nb);
	printf("size + espace + zero + prec:% 05.3ld \n", nb);
	printf("size + minus + plus + prec:%-+5.3ld \n", nb);
	printf("space% lld \n", nb);
	printf("plus:%+lld \n", nb);
	printf("precision:%.5lld \n", nb);
	printf("space + prec:% .5lld \n", nb);
	printf("Plus + prec / grande:%+.5lld \n", nb);
	printf("Prec + 0:%0.5lld \n", nb);
	printf("Prec + minus:%-.5lld \n", nb);
	printf("size:%5lld \n", nb);
	printf("size + space:% 5lld \n", nb);
	printf("size + plus:%+5lld \n", nb);
	printf("size + minus:%-5lld \n", nb);
	printf("size + 0:%05lld \n", nb);
	printf("size + 0 + plus:%+05lld \n", nb);
	printf("size + 0 + plus:%0+5lld \n", nb);
	printf("size + 0 + prec:%05.3lld \n", nb);
	printf("size + minus + prec:%-5.3lld \n", nb);
	printf("size + plus + 0 + prec:%+05.3lld \n", nb);
	printf("size + espace + zero + prec:%0 5.3lld \n", nb);
	printf("size + espace + zero + prec:% 05.3lld \n", nb);
	printf("size + minus + plus + prec:%-+5.3lld \n", nb);
	printf("space% hhd \n", nb);
	printf("plus:%+hhd \n", nb);
	printf("precision:%.5hhd \n", nb);
	printf("space + prec:% .5hhd \n", nb);
	printf("Plus + prec / grande:%+.5hhd \n", nb);
	printf("Prec + 0:%0.5hhd \n", nb);
	printf("Prec + minus:%-.5hhd \n", nb);
	printf("size:%5hhd \n", nb);
	printf("size + space:% 5hhd \n", nb);
	printf("size + plus:%+5hhd \n", nb);
	printf("size + minus:%-5hhd \n", nb);
	printf("size + 0:%05hhd \n", nb);
	printf("size + 0 + plus:%+05hhd \n", nb);
	printf("size + 0 + plus:%0+5hhd \n", nb);
	printf("size + 0 + prec:%05.3hhd \n", nb);
	printf("size + minus + prec:%-5.3hhd \n", nb);
	printf("size + plus + 0 + prec:%+05.3hhd \n", nb);
	printf("size + espace + zero + prec:%0 5.3hhd \n", nb);
	printf("size + espace + zero + prec:% 05.3hhd \n", nb);
	printf("size + minus + plus + prec:%-+5.3hhd \n", nb);
	printf("space% hd \n", nb);
	printf("plus:%+hd \n", nb);
	printf("precision:%.5hd \n", nb);
	printf("space + prec:% .5hd \n", nb);
	printf("Plus + prec / grande:%+.5hd \n", nb);
	printf("Prec + 0:%0.5hd \n", nb);
	printf("Prec + minus:%-.5hd \n", nb);
	printf("size:%5hd \n", nb);
	printf("size + space:% 5hd \n", nb);
	printf("size + plus:%+5hd \n", nb);
	printf("size + minus:%-5hd \n", nb);
	printf("size + 0:%05hd \n", nb);
	printf("size + 0 + plus:%+05hd \n", nb);
	printf("size + 0 + plus:%0+5hd \n", nb);
	printf("size + 0 + prec:%05.3hd \n", nb);
	printf("size + minus + prec:%-5.3hd \n", nb);
	printf("size + plus + 0 + prec:%+05.3hd \n", nb);
	printf("size + espace + zero + prec:%0 5.3hd \n", nb);
	printf("size + espace + zero + prec:% 05.3hd \n", nb);
	printf("size + minus + plus + prec:%-+5.3hd \n", nb);
	printf("max int :  %d", INT16_MAX);
	printf("min int :  %d", INT16_MIN);
	printf("max int :  %d", INT32_MAX);
	printf("min int :  %d", INT32_MIN);
}

int main(void)
{
	int nb = 0;
    mine(nb);
    // real(nb);
}